<?php
include $_SERVER['DOCUMENT_ROOT'] . '/letontop_kernel/letontop_functions.php';
if ($tokens !== $loginma) {
  header("location: /");
  die;
};
$xml = new SimpleXMLElement('<?xml version="1.0" encoding="utf-8"?><aboutchanges/>');
$aboutchange = $xml->addChild('aboutchange');
$aboutchange->addAttribute('type', '昵称');
$aboutchange->addChild('aboutnick', $_POST['aboutnickname']);
$aboutchange = $xml->addChild('aboutchange');
$aboutchange->addAttribute('type', '性别');
$aboutchange->addChild('aboutgender', $_POST['aboutgender']);
$aboutchange = $xml->addChild('aboutchange');
$aboutchange->addAttribute('type', '年龄');
$aboutchange->addChild('aboutage', $_POST['aboutage']);
$aboutchange = $xml->addChild('aboutchange');
$aboutchange->addAttribute('type', '职业');
$aboutchange->addChild('aboutvocation', $_POST['aboutvocation']);
$aboutchange = $xml->addChild('aboutchange');
$aboutchange->addAttribute('type', '副业');
$aboutchange->addChild('aboutsideline', $_POST['aboutsideline']);
$aboutchange = $xml->addChild('aboutchange');
$aboutchange->addAttribute('type', '公司');
$aboutchange->addChild('aboutcompany', $_POST['aboutcompany']);
$aboutchange = $xml->addChild('aboutchange');
$aboutchange->addAttribute('type', '所在地');
$aboutchange->addChild('aboutcity', $_POST['aboutcity']);
$aboutchange = $xml->addChild('aboutchange');
$aboutchange->addAttribute('type', '故乡');
$aboutchange->addChild('abouthometown', $_POST['abouthometown']);
$aboutchange = $xml->addChild('aboutchange');
$aboutchange->addAttribute('type', '邮箱');
$aboutchange->addChild('aboutemail', $_POST['aboutemail']);
$aboutchange = $xml->addChild('aboutchange');
$aboutchange->addAttribute('type', '个人说明');
$aboutchange->addChild('aboutaboutme', $_POST['aboutaboutme']);
$aboutchange = $xml->addChild('aboutchange');
$aboutchange->addAttribute('type', '通讯');
$aboutchange->addChild('aboutsocials', $_POST['aboutsocials']);
$aboutchange = $xml->addChild('aboutchange');
$aboutchange->addAttribute('type', '平台');
$aboutchange->addChild('aboutplatform', $_POST['aboutplatform']);
$aboutchange = $xml->addChild('aboutchange');
$aboutchange->addAttribute('type', '联系我');
$aboutchange->addChild('aboutcustom', $_POST['aboutcustom']);
$aboutchange = $xml->addChild('aboutchange');
$aboutchange->addAttribute('type', '联系我1');
$aboutchange->addChild('aboutcustom1', $_POST['aboutcustom1']);
$aboutchange = $xml->addChild('aboutchange');
$aboutchange->addAttribute('type', '联系我01');
$aboutchange->addChild('aboutcustom01', $_POST['aboutcustom01']);
$aboutchange = $xml->addChild('aboutchange');
$aboutchange->addAttribute('type', '联系我2');
$aboutchange->addChild('aboutcustom2', $_POST['aboutcustom2']);
$aboutchange = $xml->addChild('aboutchange');
$aboutchange->addAttribute('type', '联系我02');
$aboutchange->addChild('aboutcustom02', $_POST['aboutcustom02']);
$aboutchange = $xml->addChild('aboutchange');
$aboutchange->addAttribute('type', '联系我3');
$aboutchange->addChild('aboutcustom3', $_POST['aboutcustom3']);
$aboutchange = $xml->addChild('aboutchange');
$aboutchange->addAttribute('type', '联系我03');
$aboutchange->addChild('aboutcustom03', $_POST['aboutcustom03']);
$aboutchange = $xml->addChild('aboutchange');
$aboutchange->addAttribute('type', '兴趣爱好');
$aboutchange->addChild('abouthobby', $_POST['abouthobby']);
$aboutchange = $xml->addChild('aboutchange');
$aboutchange->addAttribute('type', '技能');
$aboutchange->addChild('aboutskill', $_POST['aboutskill']);
$aboutchange = $xml->addChild('aboutchange');
$aboutchange->addAttribute('type', '额外说明 ');
$aboutchange->addChild('aboutexplain', $_POST['aboutexplain']);
$xml->asXML($_SERVER['DOCUMENT_ROOT'] . '/content/sys/siteabout.xml');
$file1 = "/data/sys/siteinfo.xml";
$file2 = "/data/sys/conn.xml";
if (file_exists($file1) && file_exists($file2)) {
  echo '设置保存出错!';
} else {
  echo '<script>';
  echo "sessionStorage.setItem('windows','3');";
  echo "top.location.href = '/about.php';";
  echo '</script>';
}
